import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Talvi.Art</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
       <p className={styles.box}>
          <h2> Welcome to almost non-empty page! </h2>
         <p> Test text goes here, something something Talvi does art or stuff like that.
          Test test test.
          <br></br> Maybe here some stuff idk.
          <br></br>I think this is getting dumb.</p>
        <ul className={styles.ul}> ★ Working on: ★
        {/* Why doesn't this apply the style properly? */}
        <li> Name </li>
        </ul>
        <ul className={styles.ul}> ★ Waiting List: ★
        <li> Name</li>
        <li> Name</li>
        <li> Name</li>
        <li> Name</li>
        </ul>
        </p>
      </main>
    </div>
  )
}
