import Head from 'next/head'
import Page from '../components/Page'
import { SocialIcon } from 'react-social-icons';

import styles from '../styles/Home.module.css'

export default function Home() {
    return (
      <Page>
      <Head>
        <title>Talvi.Art</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <section>
        <h2> Welcome to almost soon-completed page! </h2>
          <p>25-something Finnish Artist sometimes trying her best and sometimes getting art done. At best times, even almost decent art!
            <br></br>
          Page contains both NSFW and SFW examples.
            <br></br><br></br>
          Contact me at:
          <br/><SocialIcon style={{ height: 30, width: 30 }} fgColor="#FFFFFF" bgColor='#a85c6d' network='discord'/><strong> ❥ Talvi#4702</strong>
          <br/><SocialIcon style={{ height: 30, width: 30 }} fgColor="#FFFFFF" bgColor='#a85c6d' network='email' url="mailto:talvikart@gmail.com" /> ❥ talvikart@gmail</p>
          <br></br>
          <p className={styles.ul} > <h3><b>★ Comission Status: <ins>Open</ins> ★</b></h3> </p>
        <ul className={styles.ul}> <b>★ Working on: ★</b>
        <li> Kinda want these lists into fancier form too..</li>
        </ul>
        <br />
        <ul className={styles.ul}> <b>★ Waiting List: ★</b>
        <li> Especially the waiting list one</li>
        <li> Name</li>
        <li> Name</li>
        </ul>
        </section>
    </Page>
    )
}