import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Page from '../components/Page'

export default function Prices() {
    return (
      <Page>
      <Head>
        <title>Talvi.Art</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <section>
        <h2> Welcome to almost non-empty page! </h2>
          <p>25-something Finnish Artist sometimes trying her best and sometimes getting art done. At best times, even almost decent art!
            <br></br>
          Page contains both NSFW and SFW examples.
            <br></br><br></br>
          Contacts through discord at <strong>Talvi#4702</strong> or to e-mail found at the bottom of the page.</p>
          <br></br>
          <p className={styles.ul}>
          <b><ins>★ Comission Status: ★</ins></b>
          <br></br>
          Status here. Could make it fancy with some button or smth
          </p>
          <br></br>
        <ul className={styles.ul}> <b><ins>★ Working on: ★</ins></b>
        <li> Kinda want these lists into fancier form too..</li>
        </ul>
        <ul className={styles.ul}> <b><ins>★ Waiting List: ★</ins></b>
        <li> Especially the waiting list one</li>
        <li> Name</li>
        <li> Name</li>
        </ul>
        </section>
    </Page>
    )
}